React Implementation - Sprint 2
OliOliKT/StealthStories pull request #23
Opened 2023-11-24 08:28 UTC by OliOliKT

2023-11-30 10:34 UTC, mircealungu requested changes
overall very good work!
please have a look at the comments and address the ones you can and agree with. 

mircea and @igawaclawska

2023-11-30 10:34 UTC, mircealungu commented on src/components/AccountInformation.js
> +            <span>*************</span>
why are we showing stars when the uid is not defined?

2023-11-30 10:34 UTC, mircealungu commented on src/components/AddCommentButton.js
> +        <p className="add-comment-text"> + Add comment </p>
a component should be reusable. 
This is just a hardcoded button with the text that's not changeable.
why is i a component then?

2023-11-30 10:34 UTC, mircealungu commented on src/components/ButtonAndText.css
> +.iconLink {
kebab-case?

2023-11-30 10:34 UTC, mircealungu commented on src/components/CommentComponent.js
> +const WriteComment = ({ postId, closeCommentModal, onCommentPosted }) => {
You never name a component FooComponent. It's clearly a component based on it's structure.

2023-11-30 10:34 UTC, mircealungu commented on src/components/CommentButtonAndText.js
> +    <div className="iconAndText" onClick={onComment}>
name all event handlers with `handle` maybe? as you do in the next file?

2023-11-30 10:34 UTC, mircealungu commented on src/components/CommentComponent.js
>      <section className="writeComment">
based on the code we see here there's no need for this component to exist. simply move the section inside of the CommentBox. OR/?

2023-11-30 10:34 UTC, mircealungu commented on src/components/CreateUserButtonAndText.js
> +import { useState } from "react";
looks good.

2023-11-30 10:34 UTC, mircealungu commented on src/components/FormInput.js
> +function LogInButtonAndFormInput() {
it's good practice to have same name for component and container file. (https://github.com/itu-tid/lecture-notes/blob/main/Tech-TopUps/5-Coding-Practices.md#component-and-file-in-which-it-is-defined-should-have-the-same-name)

2023-11-30 10:34 UTC, mircealungu commented on src/components/FormInput.js
> +      setError("You typed in the wrong password!");
your error message might be misleading at times. do you know why?

2023-11-30 10:34 UTC, mircealungu commented on src/components/Post.js
> +
these many empty lines tell me that you're not using format-on-save with Prettier (https://github.com/itu-tid/lecture-notes/blob/main/Tech-TopUps/5-Coding-Practices.md#install-an-automatic-formatter-and-configure-it-to-format-on-save)

2023-11-30 10:34 UTC, mircealungu commented on src/components/Post.js
> +      const query = new Parse.Query(Post);
i'm not sure i understand the 'sip' behavior. based on what i see here it alternates between 0 and 1?

2023-11-30 10:34 UTC, mircealungu commented on src/components/TwoFactorAuthentication.js
> +const TwoFactorAuthentication = () => {
:) i don't think you'll have time to implement that...

2023-11-30 10:34 UTC, mircealungu commented on src/components/writePost.js
> +        const currentUser = Parse.User.current();
this is a very roundabout way of getting the username.
why do you have to get the session? 
you have the user id in the `Parser.User.current()`. You can simply query the User table based on that. 
or am I missing something?

2023-12-15 14:56 UTC, merged

2023-12-18 18:28 UTC, jdisitu commented on src/components/AccountInformation.js
> +            <span>*************</span>
We have a hide button which toggles between the user id and the stars.

2023-12-18 18:30 UTC, jdisitu commented on src/components/AddCommentButton.js
> +        <p className="add-comment-text"> + Add comment </p>
resolved

2023-12-18 18:40 UTC, jdisitu commented on src/components/ButtonAndText.css
> +.iconLink {
on it

2023-12-18 18:41 UTC, jdisitu commented on src/components/CommentComponent.js
> +const WriteComment = ({ postId, closeCommentModal, onCommentPosted }) => {
on it

2023-12-18 18:43 UTC, jdisitu commented on src/components/CommentButtonAndText.js
> +    <div className="iconAndText" onClick={onComment}>
on it

2023-12-18 18:51 UTC, jdisitu commented on src/components/FormInput.js
> +function LogInButtonAndFormInput() {
on it

2023-12-18 18:51 UTC, jdisitu commented on src/components/FormInput.js
> +      setError("You typed in the wrong password!");
on it

2023-12-18 18:51 UTC, jdisitu commented on src/components/Post.js
> +
on it