React Implementation - Sprint 1
OliOliKT/StealthStories pull request #7
Opened 2023-11-08 11:36 UTC by OliOliKT

2023-11-09 12:47 UTC, mircealungu requested changes
overall good. a few requests for change

2023-11-09 12:47 UTC, mircealungu commented on src/components/CommentComponent.js
> +        id="comment"
Element id should be unique in the app. This looks very _un-unique_.

2023-11-09 12:47 UTC, mircealungu commented on src/components/PostFilter.js
> +import './PostFilter.css';
Nice that you're importing the styles from the corresponding css file!

2023-11-09 12:47 UTC, mircealungu commented on src/components/PostFilter.js
> +        <div id="filter">
id should be unique.

2023-11-09 12:47 UTC, mircealungu commented on src/pages/IndividualPost.css
> +.IndividualPost {
https://github.com/itu-tid/lecture-notes/blob/main/Tech-TopUps/5-Coding-Practices.md#name-your-css-classes-with-kebab-case

2023-11-24 08:25 UTC, emhberg commented
Some of these changes, like variable names and kebab case will be changes for the next sprint.

2023-11-24 08:25 UTC, closed without merging

2023-12-18 18:57 UTC, jdisitu commented on src/components/PostFilter.js
> +        <div id="filter">
on it